const constants = {
    GET_USB_DISKS: "GET_USB_DISKS",
    SET_USB_DISKS: "SET_USB_DISKS",
    GET_ADK_PATH: "GET_ADK_PATH",
    DOWNLOAD_ADK: "DOWNLOAD_ADK",
    GET_PROGRESS: "GET_PROGRESS",
    CREATE_BOOTABLE: "CREATE_BOOTABLE",
    SET_USB_PROGRESS: "SET_USB_PROGRESS",
    GET_LANG: "GET_LANG",
}
export default constants