const constants = {
ABOUT: 'ABOUT',
DEBUG:'DEBUG',
EDIT_JOB: 'EDIT_JOB',
BACKUP_SELECT_SOURCE: 'BACKUP_SELECT_SOURCE',
BACKUP_SELECT_REPOSITORY: 'BACKUP_SELECT_REPOSITORY',
RESTORE_WIZARD : 'RESTORE_WIZARD',
USB_WINDOW: 'USB_WINDOW',
QUICK_START_WINDOW: 'QUICK_START_WINDOW'
}
export default constants
