const app = {
  SET_PAGE_INDEX: 'SET_PAGE_INDEX',
  SET_LANG: 'SET_LANG',
  GET_TOKEN: 'GET_TOKEN',
  SHOW_LOADING: 'SHOW_LOADING',
  SHOW_LOADING2: 'SHOW_LOADING2',
  HIDE_LOADING: 'HIDE_LOADING',
  SET_NETWORK: 'SET_NETWORK',
  SET_NETWORK_REDUX: 'SET_NETWORK_REDUX',
  GET_DRIVERS: 'GET_DRIVERS',
  SET_DRIVERS: 'SET_DRIVERS',
  INSTALL_DRIVERS: 'INSTALL_DRIVERS',
  GET_SYS_DRIVERS: 'GET_SYS_DRIVERS',
  SET_SYS_DRIVERS: 'SET_SYS_DRIVERS',
  BROWSE_FILES: 'BROWSE_FILES',
  HOST: 'HOST',
  SET_CMP: 'SET_CMP',
  LOG_IN:'LOG_IN'
}

const auth = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_STOP: 'LOGIN_STOP',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  NON_ADMIN_USER: 'NON_ADMIN_USER',
  LOGIN_STORAGE_VAR: 'hdpuser',
  TWO_FA_LOGIN_FAILED: 'TWO_FA_LOGIN_FAILED',
  GET_SECURITY_QUESTION_SUCCESS: 'GET_SECURITY_QUESTION_SUCCESS',
  SEND_SECURITY_CODE_SUCCESS: 'SEND_SECURITY_CODE_SUCCESS',
  ANOTHER_WAY_FAILED: 'ANOTHER_WAY_FAILED',
  SET_LOGIN: 'SET_LOGIN',
  GET_SCRIPT: 'GET_SCRIPT',
  BMR_IP: 55,
  SAVE_SYS_INFO: 'SAVE_SYS_INFO',
  INFO_TOKEN: '8c6d316bbaef1605b0706d1b3bb9e3cefd42f596d32fb4e7bc08d38de7e8331d'
}

const authServiceAction = {
  LOGIN: 'LOGIN',
  LOGIN_WITH_TOKEN: 'LOGIN_WITH_TOKEN',
  LOGOUT: 'LOGOUT',
  GET_SECURITY_QUESTION: 'GET_SECURITY_QUESTION',
  SEND_SECURITY_CODE: 'SEND_SECURITY_CODE',
  TWO_FA_LOGIN: 'TWO_FA_LOGIN',
  VALIDATE_USER: 'VALIDATE_USER'
}

const wizards = {
  NETWORK_SETTINGS: 'NETWORK_SETTINGS',
  HARDWARE_DRIVER_LIST: 'HARDWARE_DRIVER_LIST',
  LOAD_DRIVE: 'LOAD_DRIVE',
  INFO_WINDOW: 'INFO_WINDOW',
  ALERT_WINDOW: 'ALERT_WINDOW',
  REPORT_WINDOW: 'REPORT_WINDOW',
  RESTORE_WIZARD: 'RESTORE_WIZARD'
}

const logAction = {
  SAVE_LOG: 'SAVE_LOG',
  GET_LOG: 'GET_LOG',
  DOWNLOAD_LOGS: 'DOWNLOAD_LOGS',
  CLEAR_LOGS: 'CLEAR_LOGS',
  DOWNLOAD_REPORT: 'DOWNLOAD_REPORT',
  GET_JOB_LOGS: 'GET_JOB_LOGS',
  SET_JOB_LOGS: 'SET_JOB_LOGS',
  SET_SELECTED_JOB_HISTORY: 'SET_SELECTED_JOB_HISTORY'
}

const windowAction = {
  OPEN_WINDOW: 'OPEN_WINDOW',
  MIN_WINDOW: 'MIN_WINDOW',
  CLOSE_WINDOW: 'CLOSE_WINDOW',
  TOP_WINDOW: 'TOP_WINDOW',
  MASK_WINDOW: 'MASK_WINDOW',
  UNMASK_WINDOW: 'UNMASK_WINDOW',
  RESTORE_WINDOW: 'RESTORE_WINDOW',
  UPDATE_METADATA: 'UPDATE_METADATA',
  UPDATE_WINDOW_MANAGER: 'UPDATE_WINDOW_MANAGER',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
}

const events = {
  ADD_SYSTEM_EVENT: 'ADD_SYSTEM_EVENT',
  ADD_JOB_EVENT: 'ADD_JOB_EVENT',
  SAVE_SYS_EVENTS: 'SAVE_SYS_EVENTS',
  SAVE_JOB_EVENTS: 'SAVE_JOB_EVENTS',
  GET_SYS_EVENTS: 'GET_SYS_EVENTS',
  GET_JOB_EVENTS: 'GET_JOB_EVENTS'
}

const globalAction = {
  CHECK_SCHEDULE_TIME: 'CHECK_SCHEDULE_TIME',
  GET_VERSION: 'GET_VERSION',
  SAVE_VERSION: 'SAVE_VERSION',
}


const windowType = {
  STANDARD: 0,
  DIALOG: 1,
}

const recovery = {
  SAVE_USB_LIST: 'SAVE_USB_LIST'
}

const statusCode = {
  success: 1,
  running: 2,
  stopped: 3,
  error: 4,
  warning: 5,
  notStarted: 6,
  disable: 8,
  inSchedule: 7,
  unknown: -1,
  workingQueue: 9,
  expired: 10,
}

const constants = {
    app,
    auth,
    authServiceAction,
    wizards,
    windowAction,
    windowType,
    logAction,
    globalAction,
    events,
    recovery,
    statusCode
  }
  
  export default constants
  
